### ISSUE TITLE
Workflow issues to consider

### ISSUE THREAD

**Issue by muratmaga** [pieper/SlicerMorphoDepot#6]
A few things:

1. Save checkpoint seems like a local commit. Is it really pushing it to the user's fork? If not, this may result in a data loss (if the local repo accidentally deleted or moved, or corrupted). 
2. What happens if the user accidentally clicks on Save and Review Request (or more likely they noticed something and want to update what they asked to be review). Then can go to the issue page  and cancel the PR, but I think we need a button to do that in the MD as well. Because I pushed it again (when was testing JS2) and it took me to a page with my existing PR.

**Comment by pieper** [comment]
Yes, once we have the basics working we need to sort out some of the other cases.  I want to keep it simple by sticking to a set flow.  Regarding your comments:

1.  Here saving a checkpoint is a local commit plus a push to the segmenter's forked repo.  Next time they open the issue it opens their local repo if it exists, and pulls from the upstream in case the PI or other segmenters have updated the main repo with material they need to see (like other peoples's segmentations).  This means that if they start on a new machine they will get the latest of their previous work and other peoples.  Because the seg.nrrd files are named for the issues there should be no overlap if everyone uses the module for their edits.

2. We can put in more status into in the MD module interface, like pending PRs that you can click and open or delete.  If you click save after the PR is already open then it will update the fork with the latest so the PR will also have that.  I think this is a good feature but probably needs to be made clear to people somehow.

In general we should also think if we want to avoid wording like "request review" in the UI and instead use github terminology of "open pull request".  It would probably make it easier to understand as people get deeper into the real github and/or we think they should use the github interface for some tasks, like commenting on PRs.

**Comment by muratmaga** [comment]
> 1. This means that if they start on a new machine they will get the latest of their previous work and other peoples.  Because the seg.nrrd files are named for the issues there should be no overlap if everyone uses the module for their edits.

This is great. That's what I wanted to make sure 

> "request review" in the UI and instead use github terminology of "open pull request".

I agree with this, but there is a learning curve as most people will not be familiar with git and github terms. Perhaps use them both? Button my say "Open Pull Request" (the proper terminology). And the popup for description says something like "Use this button to request a review of your work by the repository owner "

**Comment by muratmaga** [comment]
> Yes, once we have the basics working we need to sort out some of the other cases. I want to keep it simple by sticking to a set flow. Regarding your comments:
> 
>     1. Here saving a checkpoint is a local commit plus a push to the segmenter's forked repo.  Next time they open the issue it opens their local repo if it exists, and pulls from the upstream in case the PI or other segmenters have updated the main repo with material they need to see (like other peoples's segmentations).  This means that if they start on a new machine they will get the latest of their previous work and other peoples.  Because the seg.nrrd files are named for the issues there should be no overlap if everyone uses the module for their edits.
> 
>     2. We can put in more status into in the MD module interface, like pending PRs that you can click and open or delete.  If you click save after the PR is already open then it will update the fork with the latest so the PR will also have that.  I think this is a good feature but probably needs to be made clear to people somehow.
> 
> 
> In general we should also think if we want to avoid wording like "request review" in the UI and instead use github terminology of "open pull request". It would probably make it easier to understand as people get deeper into the real github and/or we think they should use the github interface for some tasks, like commenting on PRs.

So in this context Save Checkpoint would be commit and push? Also it would be good if we can have a short text field to enter some commit text that serve as notes...

**Comment by pieper** [comment]
Right now the github terminology is in tooltips for the buttons, but we could reverse this (hover to see the text).

About notes, yes, I thought about that too.  In fact I think we should make it a required field to have a subject line for their commit and then optional to include more description.

**Comment by amm554** [comment]
Feedback from the PI Meetings;

1. Make the issue tracking through the title not by number (or at least display the title). Instructors then ask the students to open an issue with their FullNames as title, and the specific ask in the description.
 
3. You need to filter the segmentations to be displayed. In cases where a user forks the repo after some of the  PRs are merged, the cloned repository has more than one issue-#.seg.nrrd file. All of those are displayed when the user starts working on his/her task. You need to check for presence of multiple seg.nrrd files, and only import the right issue one into the scene.

3. The reviewer issue is on going (ie., the repo owner manually need to add himself as the reviewer for a PR to show in the Review module). This is not big deal, we just have to update the documentaiton.

**Comment by muratmaga** [comment]
One more bug: 
MorphoDepot still reports the default path is unwritable. I don't think it is reading the path correctly. Once the user manually sets it, it works fine. Two options

1. Move this all the way up in the module. And make it a necessary step to set manually (if you cannot figure out why it is not reading it correctly).
2. If possible, this should default to the default Slicer Scene location setting in the Slicer.ini and probably create a subfolder there automatically. It is definitely not reading this setting on MorphoCloud (which is changed from ~/Documents to /media/volume/MyData, the persistent user storage).

**Comment by pieper** [comment]
Okay, the issues related to initializing the path should be resolved now and they will use the application's default scene path as the default.  It can only be changed in MorphoDepot's advanced setting but if you haven't changed it yet MorphoDepotReview will use the application default scene path.

In the future let's try to keep one topic per issue report so it's easier to keep track of what's been done and close what's finished.

**Comment by muratmaga** [comment]
Closing this one. Will open separate issues based on my test of your new update.
